### ISSUE TITLE
dealing with nans after smoothing

### ISSUE THREAD

**Issue by adpala** [janclemenslab/xarray-behave#63]
metrics_dataset will still produce nans in the end of the data arrays, more than those in dataset.

This happens because of the spreading of the end nans in the normal dataset after performing smoothing of the poses (lines 439-446 in xarray_behave.py):

`
```
if smooth_positions:
        # Smoothing window should span 2 frames to get smooth acceleration traces.
        # Since std of Gaussian used for smoothing has std of winlen/8, winlen should span 16 frames.
        winlen = np.ceil(16 / frame_rate * sampling_rate)
        thoraces = mt.smooth(thoraces, winlen)
        heads = mt.smooth(heads, winlen)
        wing_left = mt.smooth(wing_left, winlen)
        wing_right = mt.smooth(wing_right, winlen)
```
` 

We should figure a way to deal with this in an intuitive/practical manner.

I came up with this problem when trying to select data from metrics_dataset using thresholds in poses_confidence (which come from the dpk data) which contains nans in the last 60 frames of my video.

Easy workaround at the moment is to ignore the N last frames, where N is big enough to not see nans in any of the datasets.

**Comment by postpop** [comment]
Did you find a solution for this, @adpala ?

**Comment by adpala** [comment]
I'm still planning to try something later, but so far I just avoid the nan data post-assemble by removing a certain amount of data in the end of the array, around 200-500 frames. It is still in my TODO, but not very high priority.

**Comment by postpop** [comment]
no rush
