### ISSUE TITLE
Problem with saving swap flies

### ISSUE THREAD

**Issue by sarathnayar** [janclemenslab/xarray-behave#71]
Way to reproduce

Recording: localhost-20200707_113229
In xarray-behave gui, select swap flies (this works). 
Select File -> Save swap flies
Throws exception:
`Traceback (most recent call last):
  File "c:\users\ravindrannai\miniconda3\envs\xb_gui\lib\site-packages\xarray_behave\gui\app.py", line 804, in <lambda>
    menuitem.triggered.connect(lambda: callback(qt_keycode))
  File "c:\users\ravindrannai\miniconda3\envs\xb_gui\lib\site-packages\xarray_behave\gui\app.py", line 112, in save_swaps
    savefilename = Path(self.ds.attrs['root'], self.ds.attrs['res_path'],
KeyError: 'root'`

Expected behavior:
A window to browse to the folder to save the swap flies

**Comment by postpop** [comment]
Works for me when I open the recorder via the command line:
`xb dat/localhost-20200707_113229`
Make sure that you have the latest version installed (0.8.16).
