### ISSUE TITLE
Load the automatically annotated song events to data structure or with GUI

### ISSUE THREAD

**Issue by stein-e** [janclemenslab/xarray-behave#81]
I assume, the register_provider does not load automatically annotated vibrations. With the latest xarray_behave version, I did xb.assemble() with 'localhost-20201116_090850' which also provides a 'localhost-20201116_090850_vibration.h5' in the res file but no vibration event_types or _categories occur in the data structure. Moreover, none of the vibration annotations are shown when loading the file in the GUI.

**Comment by postpop** [comment]
vibrations are loaded but not added if they are empty which is the case for that file.
I agree that this is confusing - I'll change this behavior.
